services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
    volumes:
      - api-db:/var/lib/mysql

volumes:
  api-db: {}
